services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    env_file: .env
    environment:
      - NEXT_PUBLIC_PARQUET_URL=${R2_PUBLIC_URL}
