// Worker entrypoint fronting the MCP container (Cloudflare Containers).
//
// The container runs the canonical Python MCP server (see ../Dockerfile) on
// port 8080; this Worker forwards /mcp requests to it. The server is stateless
// (stateless_http), so requests can land on any instance.
//
// `Env` is generated by `wrangler types` (worker-configuration.d.ts) from the
// bindings in wrangler.jsonc — it types MCP_CONTAINER as the DO namespace.
import { Container, getContainer } from "@cloudflare/containers";

export class McpContainer extends Container<Env> {
  defaultPort = 8080;
  // Idle timeout before the instance is reclaimed (scale-to-zero economics).
  sleepAfter = "20m";

  // DuckDB tuning + R2 read config, all non-secret. Memory is capped under
  // standard-4's 12 GiB so a heavy query spills to the real 20 GB disk (/tmp)
  // rather than being OOM-killed.
  //
  // The Iceberg catalog (the comments system-of-record) needs a secret token and
  // is deferred to a pre-cutover step: without R2_CATALOG_* the server falls back
  // to the public comments.parquet mirror (see _attach_catalog / _resolve_catalog_config),
  // which is the full comments table too — fine for a first deploy + load test.
  envVars = {
    SPICY_REGS_MEMORY_LIMIT: "9GB",
    SPICY_REGS_TEMP_DIR: "/tmp",
    SPICY_REGS_HOME_DIR: "/tmp",
    SPICY_REGS_STATEMENT_TIMEOUT: "600s",
    SPICY_REGS_R2_URL: "https://data.spicy-regs.dev",
  };
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const { pathname } = new URL(request.url);
    if (pathname === "/mcp" || pathname.startsWith("/mcp/")) {
      return getContainer(env.MCP_CONTAINER).fetch(request);
    }
    return new Response("Not found", { status: 404 });
  },
} satisfies ExportedHandler<Env>;
