"""Generate the MCP server icon module from assets/icon.png.

The MCP spec lets a server advertise an icon on its ``Implementation`` metadata
(the name/version block sent during ``initialize``). Clients render it next to
the server in their UI.

We ship the icon as a base64 ``data:`` URI rather than an ``https://`` URL
because the server runs over two transports — ``uvx`` stdio (no HTTP origin at
all) and the Vercel HTTP deploy — and clients reject icon URLs that aren't
same-origin with the server. A ``data:`` URI is transport- and origin-
independent, so it works everywhere.

This script encodes ``assets/icon.png`` and writes the resulting URI into a
committed ``_icon.py`` module next to *each* of the two server files (the
canonical package and the parallel Vercel copy). Run it whenever the icon
changes:

    uv run python scripts/gen_icon.py
"""

from __future__ import annotations

import base64
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ICON = REPO_ROOT / "assets" / "icon.png"
MIME_TYPE = "image/png"

# Both server files keep their own committed copy so neither deploy needs the
# source PNG or this generator at build time.
TARGETS = (
    REPO_ROOT / "src" / "spicy_regs" / "_icon.py",
    REPO_ROOT / "mcp-server" / "api" / "_icon.py",
)


def build_data_uri() -> str:
    raw = SOURCE_ICON.read_bytes()
    encoded = base64.b64encode(raw).decode("ascii")
    return f"data:{MIME_TYPE};base64,{encoded}"


def render_module(data_uri: str) -> str:
    # Split the long URI into chunks, each emitted as its own quoted literal so
    # Python's implicit string concatenation reassembles them. Keeps the
    # generated file diff-friendly and under typical line-length limits.
    chunk = 96
    pieces = [data_uri[i : i + chunk] for i in range(0, len(data_uri), chunk)]
    literals = "\n".join(f'    "{piece}"' for piece in pieces)
    return (
        '"""Auto-generated by scripts/gen_icon.py — do not edit by hand.\n\n'
        "Base64 data: URI for the Spicy Regs MCP server icon (assets/icon.png).\n"
        "Regenerate with: uv run python scripts/gen_icon.py\n"
        '"""\n\n'
        "ICON_DATA_URI = (\n"
        f"{literals}\n"
        ")\n"
    )


def main() -> None:
    if not SOURCE_ICON.exists():
        raise SystemExit(f"source icon not found: {SOURCE_ICON}")

    data_uri = build_data_uri()
    module_src = render_module(data_uri)

    for target in TARGETS:
        target.write_text(module_src, encoding="utf-8")
        print(f"wrote {target.relative_to(REPO_ROOT)} ({len(data_uri)} char URI)")


if __name__ == "__main__":
    main()
